on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  markdown-lint:
    name: Validar Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Ejecutar markdownlint
        run: markdownlint "**/*.md"

  build:
    name: Build Tailwind & Jekyll
    needs: markdown-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias Node
        run: npm install

      - name: Construir Tailwind (CSS)
        run: npm run build

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Instalar dependencias Jekyll
        run: bundle install

      - name: Construir sitio con Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    name: Desplegar a GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
