name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # toda la raíz del repo, donde están tus HTML/CSS/JS

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        id: deployment
